spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.83.134/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: false
  # 序列化时not null的字段才被包含进来
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.83.134
    port: 6379
  # password:

server:
  context-path: /sell
wechat:
  #微信公众平台
  mpAppId: wxb92b6b0201ed58ae
  mpAppSecret: 94fa3da1b180d40638e7a1a5ee541142

  #微信开放平台
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e

  #微信商户平台
  mchId: 2189139182 # 微信支付开通的商户平台id
  mchKey: ssdjkfnasipfhaofhquiqoenonawn
  keyPath: /var/weixin_cert/h5.p12  #证书位置
  notifyUrl: http://sell.......... #支付结果通知地址

  #微信消息模板id
  templateId:
    orderStatus: aslkfasrwrqfsafasnalgsag


projectUrl:
  wechatMpAuthorize: http://sell.natapp4.cc
  wechatOpenAuthorize: http://sell.natapp4.cc
  sell: http://sell.natapp4.cc


logging:
  pattern:
    console: "%d - %msg%n" #日志格式
#   path: E:/log/   #输出的日志路径
#    file: E:/log/sell.log
  level:
    com.me.LoggerTest: debug
    com.me.sell.dao.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml





